### ISSUE TITLE
Problem in JDM Extension

### ISSUE THREAD

**Issue by shivam-maurya-git** [fregante/jdm#10]
When I was using JDM extension in chrome. When I visited YouTube (https://www.youtube.com/), then I clicked on extension, it takes me to "https://justdeleteme.xyz/#www.youtube.com" where it said that no solution found, because extension matches the domain name of live website to URL of a service in the "URL" section of that service in the json file.
No result found
![image](https://github.com/fregante/jdm/assets/74864959/45ed6108-8d73-4483-8ff2-bee37bc06785)

In json file "Youtube, gmail, google one, google pay" have URL value : myaccount.google.com, when I opened this page (myaccount.google.com), then I clicked extension, I got these result.
![image](https://github.com/fregante/jdm/assets/74864959/ea6817b1-8c97-48aa-afa9-533fe11be4b4)

I think I solution can be changing URL value of each service to their main website.

**Comment by fregante** [comment]
Thank you for the report!
This is not an issue with the extension, but with JDM itself:

- https://github.com/jdm-contrib/jdm/issues/1783
